name: test2
channels:
  - conda-forge
  - defaults
dependencies:
  - gspread=3.1.0
  - gspread-formatting=0.0.7
  - httplib2=0.12.0
  - oauth2client=4.1.3
  - python=3.6.5
  - requests=2.21.0
  - urllib3=1.22
  - h5py=2.9.0
  - matplotlib=3.0.3
